CONFIG_CPP=y
CONFIG_STD_CPP20=y
CONFIG_HEAP_MEM_POOL_SIZE=0
CONFIG_STACK_CANARIES=y
CONFIG_PM=y

CONFIG_STACK_CANARIES=y
CONFIG_TEST_RANDOM_GENERATOR=y
CONFIG_ENTROPY_GENERATOR=y

CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_SHELL_PROMPT_UART="med-device:~$ "

CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_NVS=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y

CONFIG_THREAD_ANALYZER=y
CONFIG_THREAD_ANALYZER_AUTO=n
CONFIG_THREAD_ANALYZER_RUN_UNLOCKED=y
CONFIG_THREAD_NAME=y

CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=n
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_LINE_CTRL=y
CONFIG_USB_DEVICE_PID=0x0001
CONFIG_USB_DEVICE_VID=0x2FE3

CONFIG_PM_DEVICE=y
CONFIG_COUNTER=y
CONFIG_COUNTER_RTC_STM32=y

CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y

CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_GLIBCXX_LIBCPP=y
CONFIG_WATCHDOG=y

CONFIG_USB_DEVICE_PRODUCT="Medical Firmware"
CONFIG_USB_DEVICE_MANUFACTURER="STM Microelectronics"

CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_REBOOT=y
