# boards/netduinoplus2.conf

# 1. Enable Simulated Flash and NVS mapping
CONFIG_FLASH_SIMULATOR=y
CONFIG_FLASH_MAP=y

# 2. Turn off USB because QEMU has no physical USB hardware controller
CONFIG_USB_DEVICE_STACK=n

# 3. Disable physical STM32-specific hardware drivers forced by prj.conf
CONFIG_COUNTER_RTC_STM32=n
CONFIG_IWDG_STM32=n
CONFIG_I2C_STM32=n
CONFIG_MPU_ALLOW_FLASH_WRITE=n

# 4. Disable Deep Sleep Power Management (not supported by QEMU's STM32 model)
CONFIG_PM=n
CONFIG_PM_DEVICE=n
