# boards/qemu_cortex_m3.conf

# 1. Simulated Flash and NVS
CONFIG_FLASH=y
CONFIG_FLASH_SIMULATOR=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y

# 2. General Subsystems
CONFIG_REBOOT=y
CONFIG_COUNTER=y
CONFIG_I2C=y
CONFIG_TEST_RANDOM_GENERATOR=y
CONFIG_WATCHDOG=y

# 3. Standard Console & C++ (Required for QEMU output)
CONFIG_CPP=y
CONFIG_STD_CPP20=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_LOG_BUFFER_SIZE=8192
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_HW_STACK_PROTECTION=y
CONFIG_ISR_STACK_SIZE=512
CONFIG_SHELL_STACK_SIZE=1024
