# boards/qemu_cortex_m3.conf

# 1. Simulated Flash and NVS
CONFIG_FLASH=y
CONFIG_FLASH_SIMULATOR=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y

# 2. General Subsystems
CONFIG_REBOOT=y
CONFIG_COUNTER=y
CONFIG_I2C=y

# 3. Disable physical hardware drivers to silence prj.conf warnings
CONFIG_WATCHDOG=n
CONFIG_PM=n
CONFIG_MPU_ALLOW_FLASH_WRITE=n
CONFIG_COUNTER_RTC_STM32=n
CONFIG_USB_DEVICE_STACK=n

# 4. Standard Console & C++ (Required for Smoke Test marker)
CONFIG_CPP=y
CONFIG_STD_CPP20=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y
