name: proj

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-verify:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Initialize Zephyr Workspace
        run: |
          west init -l .
          west update
          
          west zephyr-export
          
          SDK_DIR=$(ls -d /opt/toolchains/zephyr-sdk-* | head -n 1)
          $SDK_DIR/setup.sh -c
          
      - name: Cross Compile for STM32 ARM
        run: |
          west build -b nucleo_f207zg . --pristine
          
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtest-dev qemu-system-arm
      
      - name: Emulation Test via QEMU (STM32 Cortex-M4)
        run: |
          # 1. Compile the firmware for the STM32F405 target
          west build -b netduinoplus2 . --pristine
          
          # 2. Run the compiled binary directly using standard QEMU
          # The timeout acts as our success condition (10s of stable execution)
          timeout 10s qemu-system-arm -machine netduinoplus2 -nographic -kernel build/zephyr/zephyr.elf || if [ $? -eq 124 ]; then echo "Firmware booted successfully!"; exit 0; else echo "Firmware crashed!"; exit 1; fi
      
      - name: Host GTest & Coverage Generation
        run: |
          mkdir -p tests/build
          cd tests/build
          cmake ..
          make -j$(nproc)
          
          ./run_pm_tests
          ./run_usb_shell_tests
          ./run_battery_tests
          ./run_static_memory_tests
          ./run_config_tests
          ./run_i2c_faults_tests
          ./run_state_machine_tests
          ./run_sync_tests
          ./run_command_tests
        
      - name: Enforce 100% Line + Branch Coverage
        run: |
          chmod +x ./scripts/check_coverage.sh
          ./scripts/check_coverage.sh
      
      - name: Archive Coverage HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Coverage-Dashboard
          path: coverage_report/
